import Head from "next/head";
import Sidebar from "@/components/sidebar";
import Widget from "@/components/widget";
//import styles from "@/styles/Home.module.css";
import { HomeProps, NewsData, RandomUser } from "@/type/postType";
import { GetServerSideProps } from "next";
import CommitModel from "@/components/commitModel";
import { ArrowLeftIcon } from "@heroicons/react/outline";
import { useRouter } from "next/router";
import Post from "@/components/post";
import { useEffect, useState } from "react";
import { db } from "@/firebase";
import {
  DocumentData,
  doc,
  getDoc,
  onSnapshot,
  query,
  collection,
  orderBy,
} from "firebase/firestore";
import Comment from "@/components/commits";
import { AnimatePresence, motion } from "framer-motion";

export default function PostPage({
  newsData,
  randomUserData,
}: {
  newsData: any;
  randomUserData: any;
}) {
  const [postUser, setPosts] = useState<DocumentData | undefined>([]);
  const router = useRouter();
  const { id }: any = router.query;
  const [commits, setCommits] = useState<DocumentData>([]);
  useEffect(
    () =>
      onSnapshot(doc(db, "posts", `${id}`), (snapshot) =>
        setPosts(snapshot.data())
      ),
    [db, id]
  );
  // get all commits from the post
  useEffect(() => {
    onSnapshot(
      query(
        collection(db, "posts", `${id}`, "commits"),
        orderBy("timestamp", "desc")
      ),
      (snapshot) => setCommits(snapshot.docs)
    );
  }, [db, id]);

  return (
    <>
      <Head>
        <title>Post page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/twitter_logo.svg" />
      </Head>
      <main className="flex min-h-screen mx-auto ">
        {/** sidebar here */}
        <Sidebar />
        {/**Feed section */}
        <div className="xl:ml-[340px] border-x border-gray-200 xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl ">
          <div className="flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
            <div className="hoverEffect" onClick={() => router.push("/")}>
              <ArrowLeftIcon className="h-5  " />
            </div>
            <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
              Tweet
            </h2>
          </div>
          {postUser && <Post id={id} post={postUser} />}
          {commits.length > 0 && (
            <div className="">
              <AnimatePresence>
                {commits.map((commit: any) => (
                  <motion.div
                    key={commit.id}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 1 }}
                  >
                    <Comment
                      key={commit.id}
                      commitId={commit.id}
                      originalPostId={id}
                      commit={commit.data()}
                    />
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          )}
        </div>
        {/** Widgets */}
        <Widget newsData={newsData.articles} randomUserData={randomUserData} />

        {/** Model for commits */}
        <CommitModel />
      </main>
    </>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/health/in.json
export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  // Fetch random user data from the API
  const randomUserData: RandomUser = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  ).then((res) => res.json());

  // Fetch news data from the API
  const newsData: NewsData = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());

  return {
    props: {
      newsData,
      randomUserData,
    },
  };
};
