import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Sidebar from "@/components/sidebar";
import Feed from "@/components/feed";
import Widget from "@/components/widget";
//import styles from "@/styles/Home.module.css";
import { HomeProps, NewsData, RandomUser } from "@/type/postType";
import { GetServerSideProps } from "next";
import CommitModel from "@/components/commitModel";

export default function Home({
  newsData,
  randomUserData,
}: {
  newsData: any;
  randomUserData: any;
}) {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/twitter_logo.svg" />
      </Head>
      <main className="flex min-h-screen mx-auto ">
        {/** sidebar here */}
        <Sidebar />
        {/** Feed Section */}
        <Feed />
        {/** Widgets */}
        <Widget newsData={newsData.articles} randomUserData={randomUserData} />

        {/** Model for commits */}
        <CommitModel />
      </main>
    </>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/health/in.json
export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  // Fetch random user data from the API
  const randomUserData: RandomUser = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  ).then((res) => res.json());

  // Fetch news data from the API
  const newsData: NewsData = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());

  return {
    props: {
      newsData,
      randomUserData,
    },
  };
};
