import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Sidebar from "@/components/sidebar";
import Feed from "@/components/feed";
//import styles from "@/styles/Home.module.css";

//const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/twitter_logo.svg" />
      </Head>
      <main className="flex min-h-screen max-w-7xl mx-auto ">
        {/** sidebar here */}
        <Sidebar />
        {/** Feed Section */}
        <Feed />
      </main>
    </>
  );
}
